name: acdau2025-demo
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: codebuild-acdau2025-${{ github.run_id }}-${{ github.run_attempt }}

    env:
      STACK_NAME: acdau2025-stack
      CHANGE_SET_NAME: changeset-${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint CloudFormation template
        run: cfn-lint cfn.yaml

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://cfn.yaml

      - name: Deploy Cloudformation
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --region ap-southeast-2 \
            --template-file cfn.yaml \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_NAMED_IAM
